//HintName: Cenum.EnumerationAttribute.g.cs
// <auto-generated />
namespace Cenum
{
    [global::System.AttributeUsage(AttributeTargets.Class, Inherited = false)]
    public sealed class EnumerationAttribute : global::System.Attribute
    {
    }
}
