//HintName: EnumerationNamespace.EnumerationClass.g.cs
// <auto-generated />
namespace EnumerationNamespace
{
    public partial class EnumerationClass
    {
        public static global::System.Collections.Generic.IEnumerable<EnumerationClass> Enumerate()
        {
            yield return One;
            yield return Two;
            yield return Three;
        }
    }
}
