//HintName: GlobalEnumerationClass.g.cs
// <auto-generated />
public partial class GlobalEnumerationClass
{
    public static global::System.Collections.Generic.IEnumerable<GlobalEnumerationClass> Enumerate()
    {
        yield return One;
    }
}
