namespace Cenum;

internal class Marker
{
    public static readonly Marker Default = new("Cenum", "EnumerationAttribute");
    private readonly string _className;
    private readonly string _classNamespace;

    private Marker(string classNamespace, string className)
    {
        _classNamespace = classNamespace;
        _className = className;
    }

    public string HintName => $"{MetadataName}.g.cs";
    public string MetadataName => $"{_classNamespace}.{_className}";

    public override string ToString()
    {
        return $$"""
                 // <auto-generated />
                 namespace {{_classNamespace}}
                 {
                     [global::System.AttributeUsage(AttributeTargets.Class, Inherited = false)]
                     public sealed class {{_className}} : global::System.Attribute
                     {
                     }
                 }
                 """;
    }
}