//HintName: InternalGlobalEnumerationClass.g.cs
// <auto-generated />
internal partial class InternalGlobalEnumerationClass
{
    public static global::System.Collections.Generic.IEnumerable<InternalGlobalEnumerationClass> Enumerate()
    {
        yield return One;
        yield return Two;
        yield return Three;
    }
}
