//HintName: EnumerationNamespace.InternalEnumerationClass.g.cs
// <auto-generated />
namespace EnumerationNamespace
{
    internal partial class InternalEnumerationClass
    {
        public static global::System.Collections.Generic.IEnumerable<InternalEnumerationClass> Enumerate()
        {
            yield return One;
            yield return Two;
            yield return Three;
        }
    }
}
