//HintName: EnumerationNamespace.EmptyEnumerationClass.g.cs
// <auto-generated />
namespace EnumerationNamespace
{
    public partial class EmptyEnumerationClass
    {
        public static global::System.Collections.Generic.IEnumerable<EmptyEnumerationClass> Enumerate()
        {
            return global::System.Linq.Enumerable.Empty<EmptyEnumerationClass>()
        }
    }
}
